---
title: "Soccer Births"
author: "Fahim Ahmed"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
library(lubridate)
```

```{r, include = FALSE}
birthdates <- read_csv("birthdates.csv",
                       col_types = cols(value = col_character()))
```

```{r, echo = FALSE}
birthdates %>%
  mutate(birth_date = str_sub(value, 2, 11)) %>%
  mutate(birth_date = parse_date(birth_date)) %>%
  mutate(month = month(birth_date)) %>%
  group_by(month) %>%
  summarize(total = n()) %>%
  ggplot(mapping = aes(x = month, y = total)) +
    geom_col() +
    scale_x_continuous(breaks = 1:12) +
    theme_classic() +
    labs(title = "Birth Months of UEFA Euro 2020 Soccer Players",
         subtitle = "Most of the UEFA Euro 2020 soccer players are born in March",
         x = "Month",
         y = "Number of Players",
         caption = "Wikipedia")
  
```

```{r, include = FALSE}
birthdates %>%
  mutate(birth_date = str_sub(value, 2, 11)) %>%
  mutate(birth_date = parse_date(birth_date)) %>%
  mutate(raw_month = months(birth_date)) %>%
  mutate(month = parse_factor(raw_month, levels = month.name)) %>%
  group_by(month) %>%
  summarize(total = n()) %>%
  ggplot(mapping = aes(x = month, y = total)) +
    geom_col() +
    coord_flip() +
    theme_classic() +
    labs(title = "Birth Months of UEFA Euro 2020 Soccer Players",
         subtitle = "Most of the UEFA Euro 2020 soccer players are born in March",
         x = "Month",
         y = "Number of Players",
         caption = "Wikipedia")
```

